### PR TITLE
Delete time entry

### PR DESCRIPTION
**Pull request by jonhilt**
This is the feature built in [this walkthrough](https://practicaldotnet.vids.io/videos/709ddbb01f1ee7c2f9/architecture-mp4) to show how to implement a feature with this architecture.

### CODE REVIEW

**Comment by DotNetDublin** [comment]
Hi @jonhilt

Are you happy for this to be merged into the main branch?

Thanks

**Comment by DotNetDublin** [comment]
Hi @jonhilt

You can ignore my previous comment.

I hope this is the correct approach however I've added a commit which adds a Handler for the Delete command.

On a more minor note I've also changed the delete button to an icon as shown below.

**Comment by jonhilt** [comment]
Yep, looks good to me!

Just so you know, we're having a tough end to the week with my daughters
treatment, so I may be a bit quiet for a few days 👍

**Comment by DotNetDublin** [comment]
Thanks for getting back and sorry to hear your daughter is having a tough week. Please don't give the project a second thought in such times.

**Comment by harperjohn** [comment]
I pulled the latest and got it working on my computer. Nice job adding the delete and replacing the button with the icon!!! 

Note @DotNetDublin  at first this pull did not work on my computer...

Now that I am familiar with the issue, it was easy to find the problem... but it would be nice to have a "real" solution.

The change in the db connection string from  "(localdb)\\mssqllocaldb" to " localhost",  broke the app on my computer... 

Is there a reason for this switch? I guess I could move my database on my computer, but I was wondering if there was a better way to easily/gracefully handle our various db connections strings.  Seems a bit tedious to have to always manually fix the connection string after every new pull.

**Comment by DotNetDublin** [comment]
That's funny @harperjohn as I put in localhost to avoid the very issues that you encountered and the pain of having to change it each time.

My database server name is DESKTOP-SC9J8P7 and "(localdb)\mssqllocaldb" wouldn't work for me and usually I use DESKTOP-SC9J8P7 however I noticed that localhost worked so I was hoping that might work for everyone and therefore avoid people having to change the connection each time they pulled a branch but obviously not.

I'll add an issue later and we can see if there are clever ways to manage this.

**Pull request merged**
